### ISSUE TITLE
Readme is gone and the project doesn't launch in chrome.

### ISSUE THREAD

**Issue by jakeingit** [LemonPi/DAD#1]
There was a link to a readme paired with this project on the developer's page. The test.html doesn't launch properly while launched in Chrome. It displays only the yellow menu of load/save and randomize character buttons.

**Comment by jakeingit** [comment]
It also doesn't open in firefox. What happened here?

**Comment by jakeingit** [comment]
Downloading the project from github brings me issues. The Readme is at http://johnsonzhong.me/DAD/update/2016/03/12/introduction.html

However, downloading the project on your site instead seems to work.

**Comment by LemonPi** [comment]
Cannot replicate; can you try now? Maybe github (hoster) was down.

**Comment by jakeingit** [comment]
When I clone to desktop, it didn't work. Going to your website allowed it
to work. If it works for you, then it works for everybody else.

**Comment by LemonPi** [comment]
Ah turns out I set the default branch on github to be master when it should've been gh-pages, which is the local branch that has been updating. It should work fine now if you clone.
